CLUT-9, CLUT-10 : Build simple list of episodes screen, Build list of episodes cell.
Rieon/Clutch pull request #1
Opened 2018-09-14 09:13 UTC by Rieon

refactoring, add progress bar and restore button

2018-09-14 11:36 UTC, FlareKin requested changes

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/model/Episode.swift
> +    let num:Int
p0: code style: leave a space between the property declaration and the type:
let num: Int

2018-09-14 11:36 UTC, FlareKin commented on viYarn/AppDelegate.swift
> +        let rootViewController = EpisodeTableViewController(nibName: nil, bundle: nil)
p0: Replace with EpisodeTableViewController()

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/model/Episode.swift
> +    let progressCompleate:Int
p0: error: progressCompleate -> progressComplete

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/model/Episode.swift
> +    let desc:String
p1: I would use description instead of desc. It is more clear to understand.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +    static let CELL_KEY = "episode"
p0: codeStyle: lets rename it to cellID instead of CELL_KEY

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +    weak var delegate:EpisodeDelegate?
p0: Remove it.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +        btn.addTarget(self, action: #selector(onClickRestore), for: .touchUpInside)
p0: Remove target.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
>      override func awakeFromNib() {
p0: Remove override. We don't use it anywhere.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +    var episode: Episode?
p0: View should not contain model inside.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +    @objc func onClickRestore(){
p0: Let's remove it for now.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
> +        if data.progressCompleate > 0{
p0: Let's create two separate buttons and change their visibility here.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/AppDelegate.swift
>          window?.rootViewController = UINavigationController(rootViewController: rootViewController)
p0: Let's remove nav controller for now. We don't need to handle it inside VCs. Instead make EpisodesController a rootViewController.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
>          btnRestore.translatesAutoresizingMaskIntoConstraints = false
p0: Remove configuration code into an init with closure that returns.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
>          containerInfo.translatesAutoresizingMaskIntoConstraints = false
p0: Remove configuration code into an init with closure that returns.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
>          txtTitle.textColor = #colorLiteral(red: 1, green: 0, blue: 0.4588235294, alpha: 1)
p0: Remove configuration code into an init with closure that returns.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewCell.swift
>          txtDesc.textColor = #colorLiteral(red: 1, green: 1, blue: 1, alpha: 1)
p0: Remove configuration code into an init with closure that returns.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewController.swift
> +        if let cell:EpisodeTableViewCell = tableView.dequeueReusableCell(withIdentifier: EpisodeTableViewCell.CELL_KEY) as? EpisodeTableViewCell
p0: code style: use type inference.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/EpisodeTableViewController.swift
> +            cell.backgroundColor = colorBackground
p0: Create a func configured(with episode: Episode) -> CellType, in which we will configure cell UI.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/ProgressBarView.swift
> +        self.backgroundColor = #colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
p0: Make progressView a let, move configuration into a closure that returns.

2018-09-14 11:36 UTC, FlareKin commented on viYarn/Episode/view/ProgressBarView.swift
> +    func setProgress(value:Int){
p0: replace with setProgress(to progress: Int, fromWidth width: CGFloat)

2018-09-14 15:07 UTC, FlareKin approved these changes

2018-09-14 15:12 UTC, merged

2018-09-15 00:21 UTC, bsuvorov commented
p0 - два JIRA ticket в одном PR. не идеально, надо разбивать. @FlareKin  - будь аккуратнее. помни о своем code review bonus ;).