CLUTCH-13: Wire up the list episodes screen with real data.
Rieon/Clutch pull request #9
Opened 2018-09-22 19:39 UTC by Rieon

2018-09-23 03:39 UTC, bsuvorov commented on viYarn/Episode/model/Episode.swift
> +        let isParsedSuccessfully = successText == "ok" ? true : false
p0:

let isParsedSuccessfully = successText == "ok" ? true : false 
to
let isParsedSuccessfully = successText == "ok"

2018-09-23 03:40 UTC, bsuvorov commented on viYarn/Episode/model/Episode.swift
> +    let isParsedSuccessfully: Bool
p0: question: а зачем нам нужен isParsedSuccessfully?

What problem are we solving?

If we fail to parse it, should we simply return nil?

2018-09-23 03:41 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +            self.delegate?.didLoadEpisodes()
p0: зачем делегаты? Может будем completion блоки использовать вместо делегатов?

2018-09-23 03:41 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +            if loadedEpisodes.isParsedSuccessfully {
p0: question: кажется что-то не дописано здесь

2018-09-23 03:43 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +        networkProvider.episodes(withHost: host, storyID: storyID, success: { [unowned self] (loadedEpisodes) in
p1: мне кажется глагол в названии функций очень помогает.
networkProvider.episodes => networkProvider.getEpisodes

также пользуйся тем что это Свифт, а не C. т/е не storyID, а можно сразу давать forStory.
networkProvide.getEpisodes(forStory: story, completion: ((episodes, error) -> ()) )

2018-09-23 03:44 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +        networkProvider.episodes(withHost: host, storyID: storyID, success: { [unowned self] (loadedEpisodes) in
p1: withHost: - let's inject that into networkProvider itself. @FlareKin  thoughts?

2018-09-23 04:19 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +            "json": "core.get_posts",
p1: такое чувство, что это будет часто повторяющийся код. будут небольшие отличия в значениях. было бы неплохо сразу вынести в отдельный метод @FlareKin  - смотри, вот такая маленькая мелочь и она один APIClient облегчает это.

2018-09-23 04:21 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +        currentRequest = Alamofire.request(url, parameters: parameters).responseString { (response) in
p0:  используй responseJSON вместо .responseString, чтобы не возиться с data / serializedData

2018-09-23 04:21 UTC, bsuvorov commented on viYarn/Episode/model/Episode.swift
> +            guard let post = EpisodePost(json: postJson) else { return nil}
p2: codestyle:

{ return nil}
=>
{ return nil }

2018-09-23 04:22 UTC, bsuvorov requested changes
в целом - хороший прогресс. несколько не больших p0.

2018-09-23 04:30 UTC, bsuvorov commented
Make sure you actually git add Author.swift and Episode.swift files
They're missing from this PR and build fails as a result.

<img width="819" alt="screen shot 2018-09-22 at 9 29 01 pm" src="https://user-images.githubusercontent.com/1530544/45924201-c6946100-beae-11e8-8e8c-11a2e3aac7de.png">

2018-09-23 19:14 UTC, bsuvorov commented on viYarn.xcodeproj/xcuserdata/dmitry.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +            timestampString = "559414288.6995521"
p0: we should add default .gitignore for xcode projects.
See example online, on github (it creates by deafult for iOS projects) or take it from any other of our projects.

2018-09-23 19:14 UTC, bsuvorov commented on viYarn.xcodeproj/xcuserdata/dmitry.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +            timestampString = "559414288.6995521"
basically, we shouldn't have xcuserdata in here. no need to review your break points :)

@Rieon  - also start doing self reviews.

2018-09-23 19:15 UTC, bsuvorov commented on viYarn/Episode/model/Author.swift
> +struct Author {
@Rieon @FlareKin p0: question: почему struct, а не классы? Хотел бы разобраться.

2018-09-23 19:15 UTC, bsuvorov commented on viYarn/Episode/model/Author.swift
> +    let last_name: String
p0: style: lastName, firstName

2018-09-23 19:16 UTC, bsuvorov commented on viYarn/Episode/model/Author.swift
> +        guard let last_name = json["last_name"] as? String else { return nil }
p0: so this should be
guard let lastName = json["last_name"] as? String else { return nil }
guard let firstName = json["first_name"] as? String else { return nil }

2018-09-23 19:17 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +            didLoad()
p0: вопрос: а зачем нам кэшировать эпизоды?
это именно вопрос - не надо пока ничего в коде менять.

p0: also. didLoad - я ожидаю что мы бы туда передавали loadedEpisode

2018-09-23 19:18 UTC, bsuvorov commented on viYarn/Episode/model/EpisodesViewModelResponsibilities.swift
> +            failLoad()
p0: failLoad - было бы неплохо передавать какую-то ошибку. Пообщайся с Ваней или Сашей как это мы делаем.

2018-09-23 19:18 UTC, bsuvorov commented on viYarn/manager/APIClient.swift
> +    func request(forID: Int, typeRequest:APIClientTypeRequest, typePost:APIClientPostType, success: @escaping ([String: Any]) -> Void, failure: @escaping () -> Void) {
nice, i like it a log. good job!

2018-09-23 19:19 UTC, bsuvorov commented on viYarn/manager/APIClient.swift
> +                failure()
it'd be great to pass on errors from here via callback.

2018-09-24 08:50 UTC, bsuvorov commented on viYarn/manager/APIClient.swift
> +struct APIClient {
p0: must be class.

2018-09-24 09:56 UTC, FlareKin approved these changes
LGTM

2018-09-24 11:09 UTC, merged